import json
import pdb
import sys
import os
from tqdm import tqdm
from string import Template
from engine.base_engine import LLMEngine
import re
import argparse
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed


inst_gen_template = Template("""
You are a helpful agent for generating task instructions based on a code snippet for solving scientific data processing tasks. You need to provide a clear and concise instruction that best describes the functionality of the given code. The instruction should be written in plain English and should be detailed enough so that a person who has no knowledge of the code can understand the task and implement code for it. The instruction should not reveal too many implementation details but also should be precise and not vague. It should be a high-level description of the code's functionality. 
You should thoroughly read the scientific data processing code snippet provided, understand the underlying domain-specific concepts behind it, and generate a task instruction that makes correct use of the domain-specific language. In other words, your task instructions should be written as if they are from a domain scientist giving instructions to a junior researcher in their lab. 
The structure of the instruction should be as clear as possible: you should clearly specify the goal of the task, clearly name the exact input file/files that should be used, and the output files that should be created and where they should saved. Additionally, if the output of the program is written to a file, you should specify the format that the output should be written in, based on the implementation given in the code snippet. In cases where, based on your understanding of the code, you deem that the instruction needs more details - for example, if a certain program can use different computational methods to reach a solution - you can add guidelines about the specific method to use in the instruction. In all cases, ensure that the instruction does not include too many implementation details but also that it is precise and does not invite ambiguity or confusion. The format of your instruction should be a concise paragraph of a few lines without any sections. Keep the instruction focused on the high level scientific goal of the task and do not make reference to unnecessary details like "ensure the directory or so and so files exist". Such low level implementation details should never be part of the instruction. 

                             
Note: when specifying the output path of the program, please replace the "gold_results_auto" string with "pred_results" in the given code but keep the rest parts of the original path. For example, "benchmark_auto/kyclark_biofx_python/gold_results_auto/antibioticsai_filter_gold_results.txt" should be replaced with "benchmark_auto/kyclark_biofx_python/pred_results/antibioticsai_filter_results.txt".

Here are some examples for reference:

Example instruction 1: Localize the events from the biosignals of one participant in "ecg_1000hz.csv". Analyze the event-related features (e.g., ECG Rate, SCR Peak, Respiratory Volume per Time). Save the results to "pred_results/bio_eventrelated_100hz_analysis_pred.csv" with the following four columns: "Condition", "ECG_Rate_Mean", "RSP_Rate_Mean", and "EDA_Peak_Amplitude".

Example instruction 2: Use the data in "bio_eventrelated_100hz.csv" and "bio_resting_5min_100hz.csv" to compute heart rate variability (HRV) indices in the time-, frequency-, and non-linear domain. Find the peaks of ECG signal and extract features from three domains (i.e., time-domain, frequency-domain and non-linear domain). Save the extracterd features from these three domains to 'pred_results/hrv_analysis_pred.csv'.

Example instruction 3: Visualize the R² results comparing single-task and multi-task performance for the dataset TDC_Single_Multi_Regression.csv. Save the visualization as 'pred_results/tdc_results_visualization.png.'


Please generate the instruction based on the code snippet below.
$code
""")

eval_program_inst = Template("""
You are a helpful coding agent for generating evaluation code based on a code snippet for solving scientific data processing tasks. You will be given the instruction, the code snippet, and the result of the code execution. Your task is to generate a Python evaluation program that can evaluate the correctness of the code snippet based on the given instruction. The evaluation program should be able to read the output file generated by the code snippet and compare it with the expected output file. The evaluation program should return a boolean value indicating whether the code snippet is correct or not, and a string containing the evaluation result.

The path of the gold result file should be listed in the given code. The path of the predicted result file should be the same as gold result's path except replacing "gold_results_auto" with "pred_results".
                             
Instruction: $instruction
                             
Here are some examples:
Example eval program 1:
from sklearn.metrics import roc_auc_score

import pandas as pd

def eval():
    pred = pd.read_csv('pred_results/aai_preds.csv')
    gold = pd.read_csv('benchmark/eval_programs/gold_results/admet_ai_gold.csv')

    data_correctness = list(pred["Drug"]) == list(gold["Drug"])

    metric = roc_auc_score(gold[["Y"]], pred[["Y"]])
    threshold = 0.84

    func_correctness = metric >= threshold

    return int(data_correctness and func_correctness), str({"data_correctness": data_correctness, "func_correctness": func_correctness})

if __name__ == "__main__":
    print(eval())

Example eval program 2:
def load_results(data_path):
    results = []
    with open(data_path, 'r') as f:
        for line in f:
            line = line.strip()
            results.append(line)
    return results


def eval():
    gold_results = load_results('benchmark/eval_programs/gold_results/antibioticsai_filter_gold_results.txt')
    gold_results = set(gold_results)
    pred_results = load_results('pred_results/compound_filter_results.txt')
    pred_results = set(pred_results)

    overlap = len(pred_results.intersection(gold_results)) / len(gold_results)

    return int(overlap == 1.0), f"overlap: {overlap}"


if __name__ == '__main__':
    print(eval())

Example eval program 3:
from sklearn.metrics import mean_absolute_error
import pandas as pd

def eval():
    preds = pd.read_csv('pred_results/cell-count_pred.csv').values
    labels = pd.read_csv('benchmark/eval_programs/gold_results/cell-count_gold.csv')['count'].to_numpy()

    metric = mean_absolute_error(labels, preds)
    threshold = 30.0

    return int(metric <= threshold), f"MAE: {metric}"

if __name__ == "__main__":
    print(eval())

Please generate the evaluation code based on the code snippet below.
$code
Generated evaluation code:
""")


def process_single_result(result, args, inst_gen_template):
    """
    Process a single result from the coding agent
    
    Args:
        result: Single result dictionary from the coding agent
        args: Command-line arguments
        inst_gen_template: Template for instruction generation
        
    Returns:
        dict: Processed result data or None if skipped
    """
    if result["success"] == 0:
        return None
    
    print(f"Current file: {result['out_fname']}")
    code = result["assistant_reply"]
    
    # Initialize LLM engine with parameters
    llm_engine = LLMEngine(
        args.model_name,
        api_key=args.api_key,
        azure_endpoint=args.azure_endpoint,
        api_version=args.api_version
    )

    # Generate instruction
    user_input = [{"role": "user", "content": inst_gen_template.substitute(code=code)}]
    inst_response, _, _ = llm_engine.respond(
        user_input, 
        temperature=args.temperature, 
        top_p=args.top_p, 
        max_tokens=args.max_tokens
    )
    
    # Create output dictionary
    output_data = {
        "discipline": result["discipline"],
        "file_url": result["file_url"],
        "program_code": result["assistant_reply"],
        "instruction": inst_response,
        "gold_program_path": result["out_fname"],
        "output_fname": result["out_fname"].replace("gold_results_auto", "pred_results"),
    }
    
    return output_data


def write_to_output_file(output_file, data):
    """
    Write data to the output file in a thread-safe manner
    
    Args:
        output_file: Path to the output file
        data: Data dictionary to write
    """
    with threading.Lock():
        with open(output_file, "a") as f:
            f.write(json.dumps(data) + "\n")


def main():
    """
    Main function to process coding agent results and generate tasks
    """
    parser = argparse.ArgumentParser(description='Process coding agent results')
    
    # File and path parameters
    parser.add_argument('--input_file', type=str, default="../result/coding_agent_result_combined_claude.jsonl",
                      help='Input file containing coding agent results')
    parser.add_argument('--output_file', type=str, default="../../generated_combined_tasks_mt_sd_claude.jsonl",
                      help='Output file for generated tasks')
    parser.add_argument('--create_backup', action='store_true',
                      help='Create backup of existing output file')
    
    # API parameters
    parser.add_argument('--api_key', type=str, default=os.environ.get("AZURE_API_KEY"),
                      help='API key for the LLM service')
    parser.add_argument('--azure_endpoint', type=str, default=os.environ.get("AZURE_ENDPOINT"),
                      help='Azure endpoint for the LLM service')
    parser.add_argument('--api_version', type=str, default="2024-12-01-preview",
                      help='API version for the LLM service')
    parser.add_argument('--model_name', type=str, default="azure_o3-mini",
                      help='Model name to use')
    
    # LLM parameters
    parser.add_argument('--temperature', type=float, default=0.3,
                      help='Temperature for LLM sampling')
    parser.add_argument('--top_p', type=float, default=0.9,
                      help='Top-p parameter for LLM sampling')
    parser.add_argument('--max_tokens', type=int, default=16000,
                      help='Maximum tokens for LLM response')
    
    # Multithreading parameters
    parser.add_argument('--max_workers', type=int, default=5,
                      help='Maximum number of worker threads')
    
    args = parser.parse_args()
    
    # Create backup if requested
    if args.create_backup and os.path.exists(args.output_file):
        backup_path = args.output_file.replace(".jsonl", "_backup.jsonl")
        if os.path.exists(backup_path):
            os.remove(backup_path)
        os.rename(args.output_file, backup_path)
        print(f"Created backup at {backup_path}")
    
    # Initialize new output file if it doesn't exist
    if not os.path.exists(os.path.dirname(args.output_file)):
        os.makedirs(os.path.dirname(args.output_file))
    
    if not os.path.exists(args.output_file):
        with open(args.output_file, "w") as f:
            pass  # Create an empty file
        
    # Load instruction template
    # Note: You need to define this template according to your needs
    
    # Load coding agent results
    with open(args.input_file, 'r') as f:
        coding_agent_result = [json.loads(line) for line in f]
    
    # Process results in parallel
    with ThreadPoolExecutor(max_workers=args.max_workers) as executor:
        # Create a list to hold futures
        futures = []
        
        # Submit tasks to the executor
        for result in coding_agent_result:
            future = executor.submit(process_single_result, result, args, inst_gen_template)
            futures.append(future)
        
        # Process results as they complete
        for future in tqdm(as_completed(futures), total=len(futures), desc="Processing results"):
            output_data = future.result()
            if output_data:
                write_to_output_file(args.output_file, output_data)
    
    print(f"Processing complete. Output saved to {args.output_file}")


if __name__ == "__main__":
    main()